# Generated by Django 4.1.5 on 2023-03-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webtranfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adv_Fname', models.CharField(max_length=255)),
                ('Adv_Lname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Advisor',
            },
        ),
        migrations.CreateModel(
            name='Cur_Detail',
            fields=[
                ('Subj_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Subj_Cr', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Cur_Group',
            fields=[
                ('CG_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('CG_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cur_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ac_Year', models.DateField(verbose_name='')),
                ('Version', models.CharField(max_length=255)),
                ('Cr_total', models.IntegerField(verbose_name='')),
                ('Cr_Man', models.IntegerField(verbose_name='')),
                ('Cr_Math', models.IntegerField(verbose_name='')),
                ('Cr_Lang', models.IntegerField(verbose_name='')),
                ('Cr_Core', models.IntegerField(verbose_name='')),
                ('Cr_Basic', models.IntegerField(verbose_name='')),
                ('Cr_Main', models.IntegerField(verbose_name='')),
                ('Cr_Select', models.IntegerField(verbose_name='')),
                ('Cr_Free', models.IntegerField(verbose_name='')),
                ('Mj_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.major')),
            ],
            options={
                'db_table': 'Cur_Head',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Std_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Std_Fname', models.CharField(max_length=255)),
                ('Std_Lname', models.CharField(max_length=255)),
                ('Adv_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.advisor')),
                ('Cmj_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.coll_major')),
                ('G_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.groups')),
                ('Mj_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.major')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='UT_ID',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='student',
            name='Stdusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.user'),
        ),
        migrations.AddField(
            model_name='cur_detail',
            name='CG_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.cur_group'),
        ),
        migrations.AddField(
            model_name='cur_detail',
            name='Cur_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.cur_head'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='Advusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.user'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='Mj_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webtranfer.major'),
        ),
    ]
