# Generated by Django 4.1.5 on 2023-03-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webtranfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UT_ID',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
