# Generated by Django 4.1.5 on 2023-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webtranfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
    ]
