# Generated by Django 4.1.5 on 2023-07-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webtranfer', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
