# Generated by Django 4.1.5 on 2023-03-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webtranfer', '0002_remove_user_ut_id_delete_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='Fac_name',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='Mj_Name',
        ),
        migrations.RemoveField(
            model_name='major',
            name='Fac_name',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
